name: simplePublishToCharbonNoGemfile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  simplePublishToCharbonNoGemfile:
    uses: michaelcinquin/charbon_git-publisher/.github/workflows/simplePublishToCharbonNoGemspec.yml@master


    
